name: CI
on: 
  delete:
    paths-ignore:
      - ".github/**"
jobs:
  build:
    name: "Build PR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          yarn
          yarn build
          npx netlify-cli deploy --dir=site/public --prod

  wpt:
    name: "webpagetest analysis"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: horacioh/webPagetestAction@master
        name: "Webpagetest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_URL: https://horacioh.netlify.com
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}
    
